name: Mirror to org repo

on:
  push:
    branches: [master]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          git remote add org-mirror https://x-access-token:${{ secrets.ORG_REPO_PAT }}@github.com/EnvPol/gcomp.git
          git push org-mirror HEAD:refs/heads/master --force